version: "3.9"

services:
    app:
        container_name: crazylittlehorse-web
        image: crazylittlehorse-web
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"